name: Notify

on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true
      job_name:
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Display status
        run: |
          echo "[${{ inputs.job_name }}] Statut : ${{ inputs.status }}"
