name: pipelineflow

on:
  push:
    branches:
      - main

env:
  APP_NAME: taskflow-api
  PYTHON_VERSION: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha_court: ${{ steps.sha.outputs.sha_court }}
    steps:
      - name: Afficher le sha court
        id: sha
        run: |
          echo "APP NAME: ${APP_NAME}"
          echo "PYTHON VERSION : ${PYTHON_VERSION}"
          echo "SHA court:${GITHUB_SHA::7}"
          echo "sha_court=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        env:
          API_KEY: ${{ secrets.API_KEY}}
        run: |
          if [ -n "$API_KEY" ]; then echo "API Key disponible: ***"; fi
          echo "Tests Ok pour le commit ${{ needs.build.outputs.sha_court }}"

  notify:
    needs: [build, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline réussi
        if: needs.test.result == 'success'
        run: echo "Pipeline réussi"

      - name: Pipeline échoué
        if: needs.test.result == 'failure'
        run: echo "Pipeline échoué"

  deploy-staging:
    environment: staging
    needs: notify
    runs-on: ubuntu-latest
    steps:
      - name: Déployer en staging

        run: |
          echo "Déploiement vers ${{ secrets.STAGING_URL }}"
